<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->delete();

        DB::table('products')->insert([
            0 => [
                'id' => 1,
                'name' => 'Ultra-1.0-01.00.00 Рама',
                'position' => 4,
                'amount' => 1,
                'laser' => NULL,
                'welding' => 800,
                'assembly' => 200,
                'electricity' => 70,
                'parent_id' => NULL,
                'source_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ], 1 => [
                'id' => 2,
                'name' => 'Ultra-1.0-05.01.00 Рама кресла',
                'position' => 5,
                'amount' => 1,
                'laser' => NULL,
                'welding' => 800,
                'assembly' => 240,
                'electricity' => 40,
                'parent_id' => NULL,
                'source_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ], 2 => [
                'id' => 3,
                'name' => 'Ultra-1.0-00.00.01 Щит',
                'position' => 1,
                'amount' => 2,
                'laser' => 4,
                'welding' => NULL,
                'assembly' => NULL,
                'electricity' => 12,
                'parent_id' => NULL,
                'source_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ], 3 => [
                'id' => 4,
                'name' => 'ВИТС-3.2-01.00.00 Опора подлокотника',
                'position' => 3,
                'amount' => 2,
                'laser' => NULL,
                'welding' => 300,
                'assembly' => 120,
                'electricity' => 10,
                'parent_id' => NULL,
                'source_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ], 4 => [
                'id' => 5,
                'name' => 'Болт М6х12 ГОСТ 1231-78',
                'position' => 6,
                'amount' => 30,
                'laser' => NULL,
                'welding' => NULL,
                'assembly' => NULL,
                'electricity' => NULL,
                'parent_id' => NULL,
                'source_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ], 5 => [
                'id' => 6,
                'name' => 'ВИТС-3.2-00.00.00 Коляска-трансформер',
                'position' => 2,
                'amount' => 1,
                'laser' => NULL,
                'welding' => NULL,
                'assembly' => NULL,
                'electricity' => 300,
                'parent_id' => NULL,
                'source_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ], 6 => [
                'id' => 7,
                'name' => 'Ultra-1.0-01.00.01 Профиль основной задний',
                'position' => NULL,
                'amount' => 1,
                'laser' => 3,
                'welding' => NULL,
                'assembly' => NULL,
                'electricity' => NULL,
                'parent_id' => 1,
                'source_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ], 7 => [
                'id' => 8,
                'name' => 'Ultra-1.0-01.00.04 Ухо',
                'position' => NULL,
                'amount' => 2,
                'laser' => 4,
                'welding' => NULL,
                'assembly' => NULL,
                'electricity' => NULL,
                'parent_id' => 1,
                'source_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ], 8 => [
                'id' => 9,
                'name' => 'Ultra-1.0-01.00.08 Втулка подшипников',
                'position' => NULL,
                'amount' => 2,
                'laser' => NULL,
                'welding' => NULL,
                'assembly' => NULL,
                'electricity' => NULL,
                'parent_id' => 1,
                'source_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ], 9 => [
                'id' => 10,
                'name' => 'Ultra-1.0-01.00.04 Ухо',
                'position' => NULL,
                'amount' => 5,
                'laser' => 4,
                'welding' => NULL,
                'assembly' => NULL,
                'electricity' => NULL,
                'parent_id' => 4,
                'source_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ], 10 => [
                'id' => 11,
                'name' => 'Болт М6х12 ГОСТ 1231-78',
                'position' => NULL,
                'amount' => 20,
                'laser' => 4,
                'welding' => NULL,
                'assembly' => NULL,
                'electricity' => NULL,
                'parent_id' => 4,
                'source_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ],
        ]);
    }
}
